/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.gui;

import com.company.dao.IllnessRepository;
import com.company.entity.Illness;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author Asim Babayev
 */
public class AddIllnessFrame extends javax.swing.JFrame {
    @Autowired
    private IllnessRepository illnessRepository;

    /**
     * Creates new form AddIllnessFrame
     */
    public AddIllnessFrame() {
        initComponents();
    }
    public AddIllnessFrame(IllnessRepository illnessRepository) {
        this();
        this.illnessRepository = illnessRepository;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addIllnessInput = new javax.swing.JTextField();
        addIllnessBtn = new javax.swing.JButton();
        closeAddIllnessBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addIllnessInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addIllnessBtn.setText("Əlavə et");
        addIllnessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIllnessBtnActionPerformed(evt);
            }
        });

        closeAddIllnessBtn.setText("Bagla");
        closeAddIllnessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAddIllnessBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addIllnessInput, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeAddIllnessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addIllnessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addIllnessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addIllnessInput, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(closeAddIllnessBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAddIllnessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddIllnessBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeAddIllnessBtnActionPerformed

    private void addIllnessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIllnessBtnActionPerformed
        String illnessName = addIllnessInput.getText();
        if(illnessName!=null && !illnessName.isEmpty()){
            Illness i = new Illness();
            i.setName(illnessName);
            try{
                illnessRepository.save(i);
                addIllnessInput.setText("");
                JOptionPane.showMessageDialog(new JFrame(), "Əlavə olundu");
            }catch(Exception e){
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(),"Dialog",JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "Input bos ola bilmez");
        }
    }//GEN-LAST:event_addIllnessBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIllnessBtn;
    private javax.swing.JTextField addIllnessInput;
    private javax.swing.JButton closeAddIllnessBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
