/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.gui;

import com.company.dao.IllnessRepository;
import com.company.dao.SymptomRepository;
import com.company.entity.Illness;

import java.util.*;
import java.util.stream.Collectors;

import com.company.entity.Symptom;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author Asim Babayev
 */
public class MainFrame extends javax.swing.JFrame {

    private IllnessRepository illnessRepository;
    private SymptomRepository symptomRepository;

    /**
     * Creates new form main
     */
    public MainFrame(IllnessRepository illnessRepository,SymptomRepository symptomRepository) {
        this();
        this.illnessRepository = illnessRepository;
        this.symptomRepository = symptomRepository;
        mainTbl.setVisible(false);
    }

    private MainFrame() {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xetBtn = new javax.swing.JButton();
        setBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        illnessLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        xetBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xetBtn.setText("Xəstəlik əlavə et");
        xetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xetBtnActionPerformed(evt);
            }
        });

        setBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setBtn.setText("Simpton əlavə et");
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(xetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(setBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        searchBtn.setText("Axtar");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        mainTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mainTbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(illnessLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(searchTextField))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(illnessLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
        AddSimptonsFrame addSimptonsFrame = new AddSimptonsFrame(symptomRepository,illnessRepository);
        addSimptonsFrame.setVisible(true);
    }//GEN-LAST:event_setBtnActionPerformed

    private void xetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xetBtnActionPerformed
        AddIllnessFrame addIllnessFrame = new AddIllnessFrame(illnessRepository);
        addIllnessFrame.setVisible(true);
    }//GEN-LAST:event_xetBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String txt = searchTextField.getText();
        clearTable();
        if(txt!=null && !txt.isEmpty()){
            if(txt.contains(",")){
                String[] symptoms = txt.split(",");
                Set<Illness> illnesses = new HashSet<>();
                ArrayList<Symptom> symptomSet = (ArrayList<Symptom>) symptomRepository.findAll();
                Set<Illness> illnessSet = new HashSet<>();
                for (String s : symptoms){
                    symptomSet.stream().forEach(symptom -> {
                        if(symptom.getName().toLowerCase().contains(s.toLowerCase())){
                             illnessSet.add(symptom.getIllness());
                        }
                    });
                }
                
                showIllnesses(new ArrayList<>(illnessSet));
            }else{
                Set<Illness> illnesses = illnessRepository.getIllnessesBySymptom(txt);
                String s = "";
                for(Illness i : illnesses){
                    s = s + i.getName() + ",";
                }
                showIllnesses(new ArrayList<>(illnesses));
            }
                
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel illnessLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton setBtn;
    private javax.swing.JButton xetBtn;
    // End of variables declaration//GEN-END:variables
private void clearTable(){
    DefaultTableModel mainTable = (DefaultTableModel) mainTbl.getModel();
            mainTable.setRowCount(0);
            mainTable.setColumnCount(0);
            mainTbl.setVisible(false);
}
    private void showIllnesses(List<Illness> illnesses) {
        System.out.println(illnesses.size());
        if(illnesses != null && !illnesses.isEmpty()){
            mainTbl.setVisible(true);
        }
        DefaultTableModel mainTable = (DefaultTableModel) mainTbl.getModel();
            mainTable.setRowCount(0);
            mainTable.setColumnCount(0);
            for(Illness i : illnesses){
                mainTable.addColumn(i.getName());
                
            }
            Object[] object = new Object[illnesses.size()];
            for(int i=0;i<illnesses.size();i++){
                String s = "";
                for(int j=0;j<illnesses.get(i).getSymptoms().size();j++){
                    s = s + illnesses.get(i).getSymptoms().get(j).getName() + ",";
                }
                object[i] = s;
            }
            mainTable.addRow(object);
            mainTbl.setModel(mainTable);
            mainTable.fireTableDataChanged();
    }
}
